export const ADD_COMPONENT = 'ADD_COMPONENT';
export const SET_ACTIVE_COMPONENT_ID = 'SET_ACTIVE_COMPONENT_ID';
export const UPDATE_ACTIVE_COMPONENT = 'UPDATE_ACTIVE_COMPONENT';
export const MOVE_COMPONENT = 'MOVE_COMPONENT';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const SET_COMPONENTS = 'SET_COMPONENTS';
